name: Atualizar Feed RSS

on:
  schedule:
    # Executa o script diariamente (ajuste o cron para o intervalo desejado)
    - cron: "0 0 * * *" # Todos os dias à meia-noite UTC
  workflow_dispatch: # Permite execução manual

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Passo 4: Executar o script Python
      - name: Executar script Python
        run: python script_gerador_de_rss.py

      # Passo 5: Commit e push
      - name: Commit e push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add feed_combinado2.xml
          git commit -m "Atualizando feed automaticamente"
          git push

